# Generated by Django 5.1 on 2024-08-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jamoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=0.0007513148009015778, upload_to='about/'),
            preserve_default=False,
        ),
    ]
